### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by terryf82** [thake/avro4k-kafka-serializer#1]
Very keen to try this out in the context of a Kotlin-based Kafka Streams processor!

Are you able to provide any examples of using this in the way a SpecificAvroSerde would be used?

**Comment by xmlking** [comment]
I have a working example here https://github.com/xmlking/micro-apps/tree/develop/apps/streams-service
I am using **redpanda** as my kafka broker + schema registry 
you can start it  with `docker compose -f infra/redpanda.yml up redpanda`
and check the schema automatically created via
```bash
curl -s \
  "http://localhost:8081/subjects/all-in-topic-value/versions/1" \
  | jq .
  ```

**Comment by thake** [comment]
I've created an IT test that shows how to use it with Kafka libraries: https://github.com/thake/avro4k-kafka-serializer/blob/main/src/integrationTest/kotlin/com/github/thake/kafka/avro4k/serializer/ConfluentIT.kt
