### ISSUE TITLE
Deprecated use of AbstractKafkaAvroSerde?

### ISSUE THREAD

**Issue by terryf82** [thake/avro4k-kafka-serializer#2]
Trying to run this with _io.confluent:kafka-streams-avro-serde:5.5.0_ installed produces this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/confluent/kafka/serializers/AbstractKafkaAvroSerDe
```

I would dearly like to be able to use this and provide feedback but without any examples I am stuck trying to reproduce the logic of your tests, I am probably not even running it properly. Any help you could offer would be greatly appreciated.

**Comment by thake** [comment]
io.confluent:kafka-streams-avro-serde:5.5.0 introduced a breaking change in the API. I'm currently working on releasing a new version that is based on 5.5.0.

**Comment by thake** [comment]
Migrated to io.confluent:kafka-streams-avro-serde:5.5.0 in version 0.7.0. It should be available on maven central soon.

**Comment by terryf82** [comment]
Thanks, but I still can't get this to work without any examples to reference.
