### ISSUE TITLE
Uses of this library require @ImplicitReflectionSerializer everywhere

### ISSUE THREAD

**Issue by KushalP** [thake/avro4k-kafka-serializer#3]
Hello! As per the title, use of this library has led to me writing `@ImplicitReflectionSerializer` wherever a Kafka consumer/producer with an `KafkaAvro4kDeserializer` or `KafkaAvro4kSerializer` is present.

Is that expected behaviour and are there plans to reduce this need?

**Comment by thake** [comment]
Unfortunately, as far as I know, this is the only way to write a generic Avro4k Serializer/Deserializer as no specific type information at coding time.

**Comment by zarakay** [comment]
Just tired to upgrade to Kotlin 1.4.0... it seems that annotation is deprecated now?

**Comment by thake** [comment]
This library will be upgraded as soon as avro4k has been migrated to kotlin
1.4.0.

Zara Kay <notifications@github.com> schrieb am Di., 18. Aug. 2020, 12:06:

**Comment by thake** [comment]
Fixed with version 0.10.0 just released to maven central. This version also leverages avro4k 0.40.0 and kotlin 1.4.10
