### ISSUE TITLE
Local cache of schemas, retrieved from Schema Registry

### ISSUE THREAD

**Issue by siviae** [thake/avro4k-kafka-serializer#8]
As I can see, now every serialization requires requesting schema from registry. I think, this add significant overhead.
It would be nice to cache schemaById and vice versa in https://github.com/thake/avro4k-kafka-serializer/blob/e38b97ae6dd720b4bbae8484ce25b648cea162ef/src/main/kotlin/com/github/thake/kafka/avro4k/serializer/AbstractKafkaAvro4kSerDe.kt#L81 and https://github.com/thake/avro4k-kafka-serializer/blob/e38b97ae6dd720b4bbae8484ce25b648cea162ef/src/main/kotlin/com/github/thake/kafka/avro4k/serializer/AbstractKafkaAvro4kSerDe.kt#L87.

**Comment by cherrydev** [comment]
If you look at the subclass of `AbstractKafkaAvro4kSreDe` which is `AbstractKafkaSchemaSerDe ` you'll see that the registry client that it creates is an instance of CachedSchemaRegistryClient. Have you noticed a problem where this doesn't seem to work?

**Comment by siviae** [comment]
Yes, you're right, I've missed that one.
