### ISSUE TITLE
Impossible to create nullable serde?

### ISSUE THREAD

**Issue by cherrydev** [thake/avro4k-kafka-serializer#9]
One of the semantics of Kafka Streams is to pass a record with a null value to a table to indicate a deletion. Because Avro4kSerde is declared with the type parameter `<T : Any>` it appears that it's impossible to declare a Serde that can be used to Materialize a KTable that has deletion semantics.

**Comment by thake** [comment]
Hey @cherrydev! Thanks for opening up this issue. Indeed the generic type boundary is incorrect. It should be `<T : Any?>`  just like you said. However, as nullable information in generics get lost when compiling to JVM bytecode this should not be an issue when using Avro4kSerde to serialize/deserialize null values. Nevertheless, I'll fix the type boundary.

**Comment by cherrydev** [comment]
Yes, if I can fool the compiler into accepting my type arguments, it works
at runtime. Thank you!
